name = "Bistecca"
author = "BisteccaDiPollo"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36610bccdadaf198a99f0f00ef2408beefd66f3d988fc1ab35c2b5c850827d40"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
